#!/usr/bin/env python3
import sys
import argparse
import shutil
from pathlib import Path
import live_agent

__all__ = []
TEMPLATES_DIRNAME = "templates"
TOOLS_DIRNAME = "tools"
SETTINGS_FILENAME = "settings.json"
README_FILENAME = "README.md"


def parse_arguments(argv):
    parser = argparse.ArgumentParser(description="Bootstraps a new agent")
    args = parser.parse_args(argv[1:])

    return args


def find_templates_dir():
    lib_path = Path(live_agent.__file__)
    lib_root = lib_path.parent
    return lib_root.joinpath(TEMPLATES_DIRNAME)


if __name__ == "__main__":
    """
    Command which bootstraps an agent, adding the following:
    - `README.md`
    - `settings.json` with the basic structure
    - `tools` folder (same as `live-agent`'s)
    - `modules` folder, containing an `__init__.py` file
    """

    args = parse_arguments(sys.argv)
    templates_dir = find_templates_dir()

    shutil.copy2(templates_dir.joinpath(README_FILENAME), README_FILENAME)
    shutil.copy2(templates_dir.joinpath(SETTINGS_FILENAME), SETTINGS_FILENAME)
    shutil.copytree(templates_dir.joinpath(TOOLS_DIRNAME), TOOLS_DIRNAME)
    Path("modules").mkdir(exist_ok=True)
    Path("modules/__init__.py").touch(exist_ok=True)
