#!/bin/bash

if [ $# -eq 1 ]
then
	settings=$1
else
	select settings in src/main/settings/*.json
	do break; done
fi

if [ "$settings" == "" ]
then
	exit
fi

## Starting with memory-profiler. Requires the library `memory-profiler`
# mprof run --multiprocess --include-children src/main/live_agent.py console $settings

## Starting the agent without profiling
python src/main/live_agent.py console $settings
